/**
 * InputLibrary - Reactive Svelte 5 library for managing inputs
 *
 * Extends Library base class with input-specific functionality.
 * Stores inputs as plain objects (not class instances) for proper reactivity.
 */

import { Library } from '../Library.svelte.js';
import { Input } from '../inputs.js';
import { toCSSIdentifier } from '../css/utils.js';

export class InputLibrary extends Library {
	constructor() {
		super('webdmx-inputs');
	}

	/**
	 * Create and add a new input
	 * @param {Object} config - Input configuration
	 * @returns {Object} Created input object
	 */
	create(config = {}) {
		const name = config.name || 'Untitled Input';

		// Determine if this is a button input
		const isButton = Input.isButtonInput({ inputControlId: config.inputControlId });
		const buttonMode = config.buttonMode || 'momentary';

		// Generate CSS identifiers
		let cssClassOn = null;
		let cssClassOff = null;
		let cssClassDown = null;
		let cssClassUp = null;
		let cssProperty = null;

		if (isButton) {
			if (buttonMode === 'toggle') {
				cssClassOn = config.cssClassOn || `${toCSSIdentifier(name)}-on`;
				cssClassOff = config.cssClassOff || `${toCSSIdentifier(name)}-off`;
			} else {
				cssClassDown = config.cssClassDown || `${toCSSIdentifier(name)}-down`;
				cssClassUp = config.cssClassUp || `${toCSSIdentifier(name)}-up`;
			}
		} else {
			cssProperty = config.cssProperty || `--${toCSSIdentifier(name)}`;
		}

		const input = {
			// id will be auto-generated by base class
			name,
			inputDeviceId: config.inputDeviceId || null,
			inputControlId: config.inputControlId || null,
			inputDeviceName: config.inputDeviceName || null,
			color: config.color || null,
			buttonMode,
			cssClassOn,
			cssClassOff,
			cssClassDown,
			cssClassUp,
			cssProperty,
			order: this.items.length
		};

		return this.add(input);
	}

	/**
	 * Add an existing input (from external source)
	 * Overrides base class to handle Input class instances
	 * @param {Object} input - Input object or Input class instance
	 * @returns {Object} Added input object
	 */
	add(input) {
		// Convert Input class instance to plain object if needed
		const plainInput = input.toJSON ? input.toJSON() : input;

		// Use base class add() which handles ID generation and order
		return super.add(plainInput);
	}

	/**
	 * Update input properties
	 * @param {string} id - Input ID
	 * @param {Object} updates - Properties to update
	 * @returns {boolean} Success status
	 */
	update(id, updates) {
		// Update CSS identifiers if name or buttonMode changed
		if (updates.name !== undefined || updates.buttonMode !== undefined) {
			const input = this.get(id);
			if (!input) return false;
			
			// Apply updates temporarily to generate CSS identifiers
			Object.assign(input, updates);
			this.updateCSSIdentifiers(input);
		}

		return super.update(id, updates);
	}

	/**
	 * Find input by device and control ID
	 * @param {string} deviceId - Device ID
	 * @param {string} controlId - Control ID
	 */
	findByDeviceControl(deviceId, controlId) {
		return this.items.find(i =>
			i.inputDeviceId === deviceId && i.inputControlId === controlId
		);
	}

	/**
	 * Update CSS identifiers for an input based on its name and button mode
	 * @param {Object} input - Input object
	 */
	updateCSSIdentifiers(input) {
		const isButton = Input.isButtonInput(input);

		if (isButton) {
			if (input.buttonMode === 'toggle') {
				input.cssClassOn = `${toCSSIdentifier(input.name)}-on`;
				input.cssClassOff = `${toCSSIdentifier(input.name)}-off`;
				input.cssClassDown = null;
				input.cssClassUp = null;
			} else {
				input.cssClassDown = `${toCSSIdentifier(input.name)}-down`;
				input.cssClassUp = `${toCSSIdentifier(input.name)}-up`;
				input.cssClassOn = null;
				input.cssClassOff = null;
			}
			input.cssProperty = null;
		} else {
			// Slider/knob inputs
			input.cssProperty = `--${toCSSIdentifier(input.name)}`;
			input.cssClassDown = null;
			input.cssClassUp = null;
			input.cssClassOn = null;
			input.cssClassOff = null;
		}

		this.save();
	}

	/**
	 * Deserialize input data from storage
	 * @param {Object} inputData - Serialized input data
	 * @param {number} index - Array index for order
	 */
	deserializeItem(inputData, index) {
		// Use Input.fromJSON to handle backward compatibility
		const input = Input.fromJSON(inputData);

		// Convert to plain object
		return {
			id: input.id || crypto.randomUUID(), // Generate UUID if not present
			name: input.name,
			inputDeviceId: input.inputDeviceId,
			inputControlId: input.inputControlId,
			inputDeviceName: input.inputDeviceName,
			color: input.color,
			buttonMode: input.buttonMode,
			cssClassOn: input.cssClassOn,
			cssClassOff: input.cssClassOff,
			cssClassDown: input.cssClassDown,
			cssClassUp: input.cssClassUp,
			cssProperty: input.cssProperty,
			order: inputData.order !== undefined ? inputData.order : index
		};
	}
}
